import type { ApplicationStatus } from './contracts';

export const statusLabels: Record<ApplicationStatus, string> = {
  resume_processing: "简历解析中",
  resume_processing_failed: "简历解析失败",
  resume_review_required: "简历信息待确认",
  waiting_job_profile: "等待岗位画像",
  hard_screening_pending: "硬筛等待中",
  hard_screening_running: "硬筛运行中",
  hard_screening_review: "硬筛人工复核",
  submitted: "已提交",
  screening_running: "初步筛选运行中",
  screening_failed: "初步筛选异常",
  department_review: "部门初步筛选审核",
  first_interview_planning: "一面题单确认",
  first_interview_scheduled: "一面已排期",
  first_interview_in_progress: "一面进行中",
  first_interview_evaluation: "一面面评确认",
  hr_second_review: "HR 二面审核",
  second_interview_in_progress: "HR 二面进行中",
  second_interview_evaluation: "HR 二面评价确认",
  final_review: "最终决策",
  offer_process: "已通过",
  on_hold: "暂缓",
  manual_review: "人工复核",
  closed_rejected: "不通过",
  closed_cancelled: "招聘取消",
  resume_replaced: "简历已被覆盖"
};

export const statusTone: Record<ApplicationStatus, string> = {
  resume_processing: "bg-blue-50 text-blue-700 border-blue-200",
  resume_processing_failed: "bg-rose-50 text-rose-700 border-rose-200",
  resume_review_required: "bg-amber-50 text-amber-800 border-amber-200",
  waiting_job_profile: "bg-amber-50 text-amber-800 border-amber-200",
  hard_screening_pending: "bg-slate-100 text-slate-700 border-slate-200",
  hard_screening_running: "bg-blue-50 text-blue-700 border-blue-200",
  hard_screening_review: "bg-yellow-50 text-yellow-800 border-yellow-200",
  submitted: "bg-slate-100 text-slate-700 border-slate-200",
  screening_running: "bg-blue-50 text-blue-700 border-blue-200",
  screening_failed: "bg-rose-50 text-rose-700 border-rose-200",
  department_review: "bg-blue-50 text-blue-700 border-blue-200",
  first_interview_planning: "bg-indigo-50 text-indigo-700 border-indigo-200",
  first_interview_scheduled: "bg-indigo-50 text-indigo-700 border-indigo-200",
  first_interview_in_progress: "bg-indigo-50 text-indigo-700 border-indigo-200",
  first_interview_evaluation: "bg-indigo-50 text-indigo-700 border-indigo-200",
  hr_second_review: "bg-cyan-50 text-cyan-700 border-cyan-200",
  second_interview_in_progress: "bg-violet-50 text-violet-700 border-violet-200",
  second_interview_evaluation: "bg-violet-50 text-violet-700 border-violet-200",
  final_review: "bg-amber-50 text-amber-800 border-amber-200",
  offer_process: "bg-emerald-50 text-emerald-700 border-emerald-200",
  on_hold: "bg-orange-50 text-orange-700 border-orange-200",
  manual_review: "bg-yellow-50 text-yellow-800 border-yellow-200",
  closed_rejected: "bg-rose-50 text-rose-700 border-rose-200",
  closed_cancelled: "bg-slate-100 text-slate-700 border-slate-200",
  resume_replaced: "bg-slate-100 text-slate-600 border-slate-200"
};
